apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-react-node-app.fullname" . }}-backend
  labels:
    app: {{ include "my-react-node-app.name" . }}
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "my-react-node-app.name" . }}
    component: backend
