apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-react-node-app.fullname" . }}-config
  labels:
    app: {{ include "my-react-node-app.name" . }}
data:
  GREETING_MESSAGE: {{ .Values.config.greetingMessage | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  app.properties: |
    timeout={{ .Values.config.properties.timeout }}
    featureX={{ .Values.config.properties.featureX }}
