apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-react-node-app.fullname" . }}-frontend
  labels:
    app: {{ include "my-react-node-app.name" . }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-react-node-app.name" . }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ include "my-react-node-app.name" . }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "{{ .Values.frontend.env.apiUrl | default "/api" }}"
          readinessProbe:
            httpGet:
              path: /healthz.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz.html
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
